FROM node:18.16-alpine as build

WORKDIR /app

WORKDIR /home/app
COPY . /home/app

ENV REACT_APP_API_URL=${REACT_APP_API_URL}

RUN rm -rf node_modules
RUN npm cache clean --force
RUN npm install
RUN npm run build

FROM nginx:1.25.2-alpine

COPY --from=build /home/app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
